apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 3000  # Port exposed by the service
      targetPort: 3000  # Port on the target pod