# apiVersion: source.toolkit.fluxcd.io/v1
# kind: GitRepository
# metadata:
#   name: web-server
#   namespace: default
# spec:
#   interval: 1m
#   url: https://github.com/johnjaredprater/web_server
#   ref:
#     branch: main
#   ignore: |
#     # exclude all
#     /*
#     # include charts directory
#     !/k8s/
# ---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-server
  namespace: default
spec:
  interval: 1m0s
  prune: true
  path: ./deployment.yaml
  sourceRef:
    kind: GitRepository
    name: web_server
  targetNamespace: default
