---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: web-server
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/johnjaredprater/web_server
