---
# Tells flux to configure itself with the stuff in this repo
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: web-server
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/johnjaredprater/web_server
---
# Tells flux to monitor ./deploy/manifests & apply changes to the Kubernetes cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-server
  namespace: flux-system
spec:
  interval: 1m0s
  path: "./deploy/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: web-server
  targetNamespace: default
