name: Build

on:
  pull_request:
    branches: [ "main" ]

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v4
    -  
      name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - 
      run: npm ci
    - 
      run: npm test
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: johnjaredprater
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: johnjaredprater/web_server
        tags: |
          type=ref,event=branch
          type=ref,event=pr
    - 
      run: |
        export REACT_APP_VERSION=$DOCKER_METADATA_OUTPUT_VERSION
        npm run build --if-present
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
